#ifndef SYNPARAM_H
#define SYNPARAM_H

//
// the name of all available parameters are defined right here
//

// 0.14.4
#define LEFTEDGE                "LeftEdge"
#define RIGHTEDGE               "RightEdge"
#define TOPEDGE                 "TopEdge"
#define BOTTOMEDGE              "BottomEdge"
#define FINGERLOW               "FingerLow"
#define FINGERHIGH              "FingerHigh"
#define MAXTAPTIME              "MaxTapTime"
#define MAXTAPMOVE              "MaxTapMove"
#define MAXDOUBLETAPTIME        "MaxDoubleTapTime"
#define CLICKTIME               "ClickTime"
#define FASTTAPS                "FastTaps"
#define EMULATEMIDBUTTONTIME    "EmulateMidButtonTime"
#define VERTSCROLLDELTA         "VertScrollDelta"
#define HORIZSCROLLDELTA        "HorizScrollDelta"
#define MINSPEED                "MinSpeed"
#define MAXSPEED                "MaxSpeed"
#define ACCELFACTOR             "AccelFactor"
#define EDGEMOTIONMINZ          "EdgeMotionMinZ"
#define EDGEMOTIONMAXZ          "EdgeMotionMaxZ"
#define EDGEMOTIONMINSPEED      "EdgeMotionMinSpeed"
#define EDGEMOTIONMAXSPEED      "EdgeMotionMaxSpeed"
#define EDGEMOTIONUSEALWAYS     "EdgeMotionUseAlways"
#define UPDOWNSCROLLING         "UpDownScrolling"
#define LEFTRIGHTSCROLLING      "LeftRightScrolling"
#define UPDOWNREPEAT            "UpDownRepeat"
#define LEFTRIGHTREPEAT         "LeftRightRepeat"
#define SCROLLBUTTONREPEAT      "ScrollButtonRepeat"
#define TOUCHPADOFF             "TouchPadOff"
#define GUESTMOUSEOFF           "GuestMouseOff"
#define LOCKEDDRAGS             "LockedDrags"
#define RTCORNERBUTTON          "RTCornerButton"
#define RBCORNERBUTTON          "RBCornerButton"
#define LTCORNERBUTTON          "LTCornerButton"
#define LBCORNERBUTTON          "LBCornerButton"
#define TAPBUTTON1              "TapButton1"
#define TAPBUTTON2              "TapButton2"
#define TAPBUTTON3              "TapButton3"
#define CIRCULARSCROLLING       "CircularScrolling"
#define CIRCSCROLLDELTA         "CircScrollDelta"
#define CIRCSCROLLTRIGGER       "CircScrollTrigger"
#define CIRCULARPAD             "CircularPad"
#define PALMDETECT              "PalmDetect"
#define PALMMINWIDTH            "PalmMinWidth"
#define PALMMINZ                "PalmMinZ"
#define COASTINGSPEED           "CoastingSpeed"
#define ABSCOORDX               "AbsCoordX"
#define ABSCOORDY               "AbsCoordY"
#define VERSIONNUMBER           "VerNr"
// 0.14.5
#define SINGLETAPTIMEOUT        "SingleTapTimeout"
#define VERTEDGESCROLL          "VertEdgeScroll"
#define HORIZEDGESCROLL         "HorizEdgeScroll"
#define VERTTWOFINGERSCROLL     "VertTwoFingerScroll"
#define HORIZTWOFINGERSCROLL    "HorizTwoFingerScroll"
#define PRESSMOTIONMINZ         "PressureMotionMinZ"
#define PRESSMOTIONMAXZ         "PressureMotionMaxZ"
#define PRESSMOTIONMINFACTOR    "PressureMotionMinFactor"
#define PRESSMOTIONMAXFACTOR    "PressureMotionMaxFactor"
// 0.14.6 (none)

#endif
